#!/usr/bin/env python
# -*- coding: UTF8 -*-

PROT_NONE = 0
PROT_READ = 1
PROT_WRITE = 2
PROT_EXEC = 4
PROT_PRIVATE = 8
PROT_SHARED = 16

#Use some Windows constants for compatibility
PAGE_EXECUTE_READWRITE = PROT_EXEC | PROT_READ | PROT_WRITE
PAGE_EXECUTE_READ = PROT_EXEC | PROT_READ
PAGE_READONLY = PROT_READ
PAGE_READWRITE = PROT_READ | PROT_WRITE

PTRACE_POKEDATA = 5 
PTRACE_ATTACH = 16
PTRACE_DETACH =17
PTRACE_CONT = 7
